# Generated by Django 3.0.8 on 2020-08-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_auto_20200803_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET('ABCD'), to='control_panel.Category'),
        ),
    ]
