# Generated by Django 3.0.8 on 2020-08-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0011_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='serial',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
