# Generated by Django 3.0.8 on 2020-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0012_giftcard_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='date_created',
            field=models.DateTimeField(auto_created=True, null=True, default=None),
            preserve_default=False,
        ),
    ]
