# Generated by Django 3.0.8 on 2020-08-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0013_giftcard_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Transaction',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.Transaction'),
        ),
    ]
