# Generated by Django 3.0.8 on 2020-08-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0014_auto_20200811_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buying_price',
            field=models.FloatField(null=True),
        ),
    ]
