# Generated by Django 3.0.8 on 2020-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0015_product_buying_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Delivered', max_length=200, null=True),
        ),
    ]
