# Generated by Django 3.0.8 on 2020-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0016_auto_20200811_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
