# Generated by Django 3.0.8 on 2020-08-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0017_auto_20200811_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default='2020-08-11 23:22'),
            preserve_default=False,
        ),
    ]
