# Generated by Django 3.0.8 on 2020-08-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0018_auto_20200811_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='verified',
            field=models.BooleanField(),
        ),
    ]
